[Gateway]
Gwid = "TEST66666"
Name = "测试网关1"
Model = "GW200F"
SN = ""
Date = ""
HwVer = "1.3"
SwVer = "V1.0.34 20250307"

[[Device]]
ID = 5
Name = "红外空调"
ModelID = "11100"
Port = "COM2"
ComID = 2
Addr = "1"
Interval = 1000
Timeout = 1000
Offline = 10

[[Device]]
ID = 6
Name = "科龙精密空调"
ModelID = "11102"
Port = "COM2"
ComID = 2
Addr = "2"
Interval = 1000
Timeout = 1000
Offline = 10

[[Device]]
ID = 20
Name = "储能电池1"
ModelID = "11020"
Port = "COM5"
ComID = 5
Addr = "2"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 21
Name = "储能电池2"
ModelID = "11020"
Port = "COM5"
ComID = 5
Addr = "3"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 22
Name = "储能电池3"
ModelID = "11020"
Port = "COM5"
ComID = 5
Addr = "4"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 23
Name = "储能电池4"
ModelID = "11020"
Port = "COM5"
ComID = 5
Addr = "5"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 24
Name = "储能电池5"
ModelID = "11020"
Port = "COM5"
ComID = 5
Addr = "6"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 25
Name = "储能电池6"
ModelID = "11020"
Port = "COM5"
ComID = 5
Addr = "7"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 40
Name = "备用电池1"
ModelID = "11024"
Port = "COM6"
ComID = 6
Addr = "2"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 41
Name = "备用电池2"
ModelID = "11024"
Port = "COM6"
ComID = 6
Addr = "3"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 42
Name = "备用电池3"
ModelID = "11024"
Port = "COM6"
ComID = 6
Addr = "4"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 1
Name = "总进线计量"
ModelID = "11006"
Port = "COM1"
ComID = 1
Addr = "1"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 2
Name = "电源1计量"
ModelID = "11006"
Port = "COM1"
ComID = 1
Addr = "2"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 3
Name = "电源2计量"
ModelID = "11006"
Port = "COM1"
ComID = 1
Addr = "3"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 9
Name = "空调节能控制器"
ModelID = "11000"
Port = "VT1"
ComID = 80
Addr = "1"
Interval = 1000
Timeout = 1000
Offline = 30

[[Device]]
ID = 10
Name = "电池节能控制器"
ModelID = "11001"
Port = "VT1"
ComID = 80
Addr = "1"
Interval = 1000
Timeout = 1000
Offline = 30

[[Collect]]
ID = "COM1"
Mode = 1
Type = "COM"
Resend = 2
SwInterval = 20

[Collect.Param]
BaudRate = 2400
DataBits = 8
StopBits = 1
Parity = "E"
Timeout = 60

[[Collect]]
ID = "COM2"
Mode = 1
Type = "COM"
Resend = 2
SwInterval = 20

[Collect.Param]
BaudRate = 9600
DataBits = 8
StopBits = 1
Parity = "N"
Timeout = 60

[[Collect]]
ID = "COM3"
Mode = 1
Type = "COM"
Resend = 2
SwInterval = 20

[Collect.Param]
BaudRate = 9600
DataBits = 8
StopBits = 1
Parity = "N"
Timeout = 60

[[Collect]]
ID = "COM4"
Mode = 1
Type = "COM"
Resend = 0
SwInterval = 0

[Collect.Param]
BaudRate = 9600
DataBits = 8
StopBits = 1
Parity = "N"
Timeout = 60

[[Collect]]
ID = "COM5"
Mode = 1
Type = "COM"
Resend = 2
SwInterval = 20

[Collect.Param]
BaudRate = 9600
DataBits = 8
StopBits = 1
Parity = "N"
Timeout = 40

[[Collect]]
ID = "COM6"
Mode = 1
Type = "COM"
Resend = 2
SwInterval = 20

[Collect.Param]
BaudRate = 9600
DataBits = 8
StopBits = 1
Parity = "N"
Timeout = 40

[[Collect]]
ID = "COM7"
Mode = 1
Type = "COM"
Resend = 2
SwInterval = 20

[Collect.Param]
BaudRate = 9600
DataBits = 8
StopBits = 1
Parity = "N"
Timeout = 40

[[Collect]]
ID = "COM8"
Mode = 1
Type = "COM"
Resend = 2
SwInterval = 20

[Collect.Param]
BaudRate = 9600
DataBits = 8
StopBits = 1
Parity = "N"
Timeout = 40

[[Collect]]
ID = "COM9"
Mode = 1
Type = "COM"
Resend = 2
SwInterval = 20

[Collect.Param]
BaudRate = 9600
DataBits = 8
StopBits = 1
Parity = "N"
Timeout = 40

[[Collect]]
ID = "VT1"
Mode = 1
Type = "VT"
Resend = 2
SwInterval = 20

[Collect.Param]
BaudRate = 9600
DataBits = 8
StopBits = 1
Parity = "N"
Timeout = 1000

[[Forward]]
ID = "JR"
Name = "JR"
Protocol = "MqttDF"
Enable = 1
Certificate = "mcloud.pem"

[Forward.Params]
IP = "www.jrie.com.cn"
Port = 1883
User = "admin"
Password = "admin123"
Appid = "jinrong"
Prjcode = "TEST66666"
Prjname = "测试网关1"
Stationid = 4433222
Interval = 60
History = 100
IpAddr = "120.79.38.76"

[EMS.Bat."ems/bat1"]
CtrlMode = 0
ModuleCtrl = 0
VFCc = 53.6
VBCc = 56.5
VFCd = 50.0
VBCd = 50.1
Vhigh = 57.5
Vlow = 46.0
BatCap = 400.0
CC = 10.0
RSOC = 10.0
MSOC = 80.0
TChgAuto = 0
TChgRetry = 20

[EMS.Air]
CtrlMode = 0
TsAir = 30
TpAir = 30
Tf1Air = 25
Tf2Air = 25
Tf3Air = 30
TvAir = 20
